fragment NavbarParts on Navbar {
  navbarLinks {
    __typename
    label
    url
  }
}

fragment HomePageContentParts on HomePageContent {
  sections {
    __typename
    ... on HomePageContentSectionsCarousel {
      x
      y
      images
      mainText
      description
      button {
        __typename
        text
        url
      }
      delay
    }
    ... on HomePageContentSectionsTrustIcons {
      badges {
        __typename
        icon
        text
      }
    }
    ... on HomePageContentSectionsSingleCollectionPreview {
      collection
      numImages
    }
    ... on HomePageContentSectionsMultipleCollectionsPreview {
      titleText
      collections
    }
    ... on HomePageContentSectionsSocialMediaIntegration {
      socialMedia
      numImages
    }
    ... on HomePageContentSectionsTestimonials {
      titleText
      userTestimonials {
        __typename
        quote
        user
        website
        date
      }
    }
    ... on HomePageContentSectionsAlternatingImageBlocks {
      imageBlocks {
        __typename
        image
        titleText
        paragraphs
      }
    }
  }
}

fragment FooterParts on Footer {
  navSections {
    __typename
    links {
      __typename
      label
      url
    }
    title
  }
}
