fragment SeoParts on Seo {
  title
  description
}

fragment NavbarParts on Navbar {
  logo
  navbarLinks {
    __typename
    label
    url
  }
  fixed
  layout
}

fragment FooterParts on Footer {
  navigationRow {
    __typename
    title
    links {
      __typename
      label
      url
    }
  }
}

fragment HomePageParts on HomePage {
  sections {
    __typename
    ... on HomePageSectionsCarousel {
      images
      mainText
      description
      button {
        __typename
        text
        url
      }
      delay
    }
    ... on HomePageSectionsTrustIcons {
      badges {
        __typename
        icon
        text
      }
    }
    ... on HomePageSectionsSingleCollectionPreview {
      collection
      numImages
    }
    ... on HomePageSectionsMultipleCollectionsPreview {
      titleText
      collections
    }
    ... on HomePageSectionsSocialMediaIntegration {
      socialMedia
      numImages
    }
    ... on HomePageSectionsTestimonials {
      titleText
      userTestimonials {
        __typename
        quote
        user
        website
        date
      }
    }
    ... on HomePageSectionsAlternatingImageBlocks {
      imageBlocks {
        __typename
        image
        titleText
        paragraphs
      }
    }
  }
}

fragment TestPageParts on TestPage {
  sections {
    __typename
    title
    author
    body
  }
}
