query getSeoDocument($relativePath: String!) {
  getSeoDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...SeoParts
    }
  }
}

query getSeoList {
  getSeoList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...SeoParts
        }
      }
    }
  }
}

query getNavbarDocument($relativePath: String!) {
  getNavbarDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...NavbarParts
    }
  }
}

query getNavbarList {
  getNavbarList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...NavbarParts
        }
      }
    }
  }
}

query getFooterDocument($relativePath: String!) {
  getFooterDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...FooterParts
    }
  }
}

query getFooterList {
  getFooterList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...FooterParts
        }
      }
    }
  }
}

query getHomePageDocument($relativePath: String!) {
  getHomePageDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...HomePageParts
    }
  }
}

query getHomePageList {
  getHomePageList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...HomePageParts
        }
      }
    }
  }
}

query getTestPageDocument($relativePath: String!) {
  getTestPageDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...TestPageParts
    }
  }
}

query getTestPageList {
  getTestPageList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...TestPageParts
        }
      }
    }
  }
}
